### ISSUE TITLE
allocator: peer address filtering rules

### ISSUE THREAD

**Issue by ernado** [gortc/gortcd#25]
Something like
```yml
peers:
   - action: allow
     net: 10.22.108.13:22
   - action: drop
     net: 0.0.0.0/0
```
